# -*- coding: utf-8 -*-
"""Diwali sales.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1b_26W-x5VeSFbB5y9_Ilz1XQwzFel8AW
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

df=pd.read_csv('/content/Diwali Sales Data.csv',encoding='unicode_escape')

df.head(

)

df.info(

)

df.drop(['Status','unnamed1'],axis=1,inplace=True)

df.columns

df.isnull().sum()

df.dropna()

df.isnull().sum()

pd.isnull(df).sum()

df.dropna(inplace=True)

df.shape

df.dtypes

df['Amount']=df['Amount'].astype(int)

df.dtypes

ax=sns.countplot(x='Gender',data=df,color='red')
plt.xlabel('Gender')
plt.ylabel('Count')
plt.title('count of sale by Gender')
for bars in ax.containers:
  ax.bar_label(bars)

"""Female buy more than male"""

df.groupby(['Gender'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)

sale_gen=df.groupby(['Gender'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)

ax=sns.barplot(x='Gender',y='Amount',data= sale_gen)
for bars in ax.containers:
  ax.bar_label(bars)

"""Female spend more than male"""

df.columns

ax=sns.countplot(data=df,x='Age Group',hue='Gender')#hue for legend
for bars in ax.containers:
  ax.bar_label(bars)

"""Age group wise spend by male or female"""

sale_age=df.groupby(['Age Group'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False)

sns.barplot(data=sale_age,x='Age Group',y='Amount')

"""Age group 26-35 is spend more than other age group"""

sale_state=df.groupby(['State'],as_index=False)['Orders'].sum().sort_values(by='Orders',ascending=False).head(10)
sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data=sale_state,x='State',y='Orders')

"""State wise most order . Uttar Pradesh orders more than other state"""

sale_state=df.groupby(['State'],as_index=False)['Amount'].sum().sort_values(by='Amount',ascending=False).head(10)
sns.set(rc={'figure.figsize':(20,5)})
sns.barplot(data=sale_state,x='State',y='Amount')

"""purchase base on amount , uttar pradesh spend more than other state"""

ax=sns.countplot(x='Marital_Status',data=df,color='green')
sns.set(rc={'figure.figsize':(5,5)})
for bars in ax.containers:
  ax.bar_label(bars)

"""Married pepole Buy more than unmarried pepole"""

sale_state=df.groupby(['Marital_Status','Gender'],as_index=False)['Orders'].sum().sort_values(by='Orders',ascending=False).head(10)
sns.barplot(data=sale_state,x='Marital_Status',y='Orders',hue='Gender')

"""Female buy more than male in married pepole"""

ax=sns.countplot(data=df,x='Occupation')
sns.set(rc={'figure.figsize':(25,5)})
for bars in ax.containers:
  ax.bar_label(bars)

"""IT Sector Employe more purchase than other occupation"""

ax=sns.countplot(data=df,x='Product_Category')
sns.set({'figure.figsize':(30,5)})
for bars in ax.containers:
  ax.bar_label(bars)

"""Most buying product categories

Conclusion:
           Married women age group 26-35frm Up,Maharashtra,karnataka working in IT,Healthcare and aviation are more ;likely to buy product from food,clothing and electronics category.
"""

